spring.application.name=nerdy-logs-app
server.port=8080
review-service.url=http://localhost:8081

# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/nerdy_logs_app?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=test
logging.level.org.hibernate.persister.entity=ERROR

# Default admin
users.defaultAdmin.username=admin
users.defaultAdmin.email=admin@nerdylogs.com
users.defaultAdmin.password=admin
users.defaultAdmin.profilePicture=/images/admin-pfp.webp
users.defaultAdmin.role=ADMIN

# Default user presets
users.defaultUser.profilePicture=/images/default-pfp.jpg